organization: digitomize
stickers:
  - id: clw2i5hwq30420fmig4xp6f34
    alias: bug-hunter
holobytes:
  - evolvingStickerId: clw2hnpws09610fmf6c309nje
    alias: c-av
    icon: avocado
  - evolvingStickerId: clw2hnpws09610fmf6c309nje
    alias: c-ch
    icon: cherry
  - evolvingStickerId: clw2hnpws09610fmf6c309nje
    alias: c-st
    icon: starfruit
  - evolvingStickerId: clw2hnpws09610fmf6c309nje
    alias: c-cf
    icon: coffee
    in: true
  - evolvingStickerId: clw2hnpws09610fmf6c309nje
    alias: c-lm
    icon: lemon
    in: true
    from: true
