organization: digitomize
stickers:
  - id: clw2i5hwq30420fmig4xp6f34
    alias: bug-hunter
holobytes:
  - evolvingStickerId: clw2hnpws09610fmf6c309nje
    alias: holobyte

  - alias: av
    icon: avocado
