version: '3.0'

services:
  frontend:
    image: pranshugupta54/client:c2e03f0
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "5173:5173"
    env_file:
      - ~/secrets/frontend



  backend:
    image: pranshugupta54/backend:c2e03f0
    restart: always
    ports:
      - "4001:4001"
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - ~/secrets/backend