name: Label issues
on:
  issues:
    types:
      - opened

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check if 'gssoc' in description
        id: check-gssoc
        run: |
          if grep -q -i 'gssoc' <<< "${{ github.event.issue.body }}"; then
            echo "GSSOC keyword found in the description."
            echo "::set-output name=has_gssoc::true"
          else
            echo "GSSOC keyword not found in the description."
            echo "::set-output name=has_gssoc::false"
          fi

      - name: Check if 'swoc' in description
        id: check-swoc
        run: |
          if grep -q -i 'swoc' <<< "${{ github.event.issue.body }}"; then
            echo "SWOC keyword found in the description."
            echo "::set-output name=has_swoc::true"
          else
            echo "SWOC keyword not found in the description."
            echo "::set-output name=has_swoc::false"
          fi

      - name: Label issue with 'gssoc'
        if: steps.check-gssoc.outputs.has_gssoc == 'true'
        run: |
          gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: gssoc

      - name: Label issue with 'swoc'
        if: steps.check-swoc.outputs.has_swoc == 'true'
        run: |
          gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: swoc
