name: Check Base Branch

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check_base_branch:
    runs_on: ubuntu-latest
  
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Check base branch
      run: |
      if [[ "${{ github.event.pull_request.base.ref }}" != "main" ]]; then
        echo "Base branch is not 'main'. Exiting with non-zero status."
        exit 1
      fi