name: Check Base Branch

on:
  pull_request:
    types: [opened, edited, synchronise, reopened]
  pull_request_target:
    types: [edited]
    branches:
      - '*'

jobs:
  check_base_branch:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Check base branch
        run: |
          base_branch=${{ github.event.pull_request.base.ref }}
          echo "$base_branch"
          if [ "$base_branch" != "main" ]; then
            echo "Base branch is not 'main'. Exiting with non-zero status."
            exit 1
          fi