name: Build & Deploy
on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
            mkdir test
            cd test #enter or cd into the folder
            git clone git@github.com:digitomize/digitomize.git
            echo 'Deployment Successful to DigitalOcean'
