name: 'Greetings'

on:
  fork:
  push:
    branches: [main]
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Hello @${{ github.actor }}! 🌟 \nThanks a bunch for creating an issue. Your input is invaluable, and we're eager to collaborate with you to address the matter. Keep up the fantastic work!"
          # pr-message: "Greetings! \nThanks for your contribution 💙. \nContributors 🧑‍🤝‍🧑 like you make the open source community 🌍 such an amazing place to learn 📖, inspire 👼, and create 🎨. We will investigate 👀 and get back to you as soon as possible 👍. Just make sure you have given us sufficient information ℹ️. Keep the momentum going!"
          footer: "Don't forget to hit the :star: star button :wink:\n> [!TIP] \n> Don't forget to check our [Contributing Guidelines](https://github.com/CodeVault/CodeVault/blob/main/CONTRIBUTING.md), [PR Guidelines](./PR_GUIDELINES.md) and [Issue Guidelines](./Issue_GUIDELINES.md) for more details. \n\n[Website](https://CodeVault.com) | [Discord](https://CodeVault.com/discord) | [Twitter](https://twitter.com/intent/follow?original_referer=https://CodeVault.com&screen_name=CodeVault&tw_p=followbutton) | [Instagram](https://instagram.com/CodeVault) | [Linkedin](https://www.linkedin.com/company/CodeVault)"
